[phases.setup]
nixPkgs = ['php82', 'nodejs_20']  # Unifica Node.js 20 (elige la versión de tu package.json)

[phases.build]
cmds = ['composer install --no-dev --optimize-autoloader', 'npm install', 'npm run build']  # Solo build essentials

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=8080'