[phases.setup]
nixPkgs = ['php82', 'nodejs_20']  # Un solo nixpkgs para PHP 8.2 y Node.js 20 (ajusta a tu package.json si es 18 o 22)

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']  # Solo Composer en install

[phases.build]
cmds = ['npm install', 'npm run build', 'php artisan optimize', 'php artisan config:cache', 'php artisan route:cache', 'php artisan view:cache', 'php artisan migrate --force']  # Build con npm y Laravel optimizaciones

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=8080'  # Inicia servidor Laravel