[phases.setup]
nixPkgs = ['php82', 'php82Extensions.bcmath', 'php82Extensions.intl', 'php82Extensions.zip', 'nodejs', 'yarn']  # Ajusta a tu versión PHP; incluye Node si usas assets.
cmds = ['composer install --optimize-autoloader --no-dev --no-interaction']