[build]
builder = "nixpacks"
buildCommand = "./build-app.sh"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
numReplicas = 1

[deploy.envs]
PHP_INI_SCAN_DIR = "/conf.d:/usr/local/etc/php/conf.d"

# Variables de entorno para producción
APP_ENV = "production"
APP_DEBUG = "false"
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"
LOG_CHANNEL = "stderr"